# Generated by Django 5.1.7 on 2025-04-18 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bookLogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_be_read', 'To Be Read'), ('currently_reading', 'Currently Reading'), ('completed', 'Completed')])),
                ('rating', models.FloatField(blank=True, choices=[(0.5, '½'), (1.0, '★'), (1.5, '★½'), (2.0, '★★'), (2.5, '★★½'), (3.0, '★★★'), (3.5, '★★★½'), (4.0, '★★★★'), (4.5, '★★★★½'), (5.0, '★★★★★')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
